import type { PublicContentAsset, PublicContentPage, PublicContentSection } from "./types";
import { normalizePublicContentPage } from "./normalization";

const siteSlug = "lbl-fabrications";

const sharedAssets: Record<string, PublicContentAsset> = {
  heroCountertop: {
    id: "heroCountertop",
    category: "image",
    name: "Countertop fabrication hero",
    originalName: "countertop.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Stone countertop fabrication detail",
    url: "https://lblfabrications.com/assets/images/content/countertop.jpg",
  },
  preproduction: {
    id: "preproduction",
    category: "image",
    name: "Preproduction",
    originalName: "preproduction.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Digital preproduction planning for stone fabrication",
    url: "https://lblfabrications.com/assets/images/content/preproduction.jpg",
  },
  cutting: {
    id: "cutting",
    category: "image",
    name: "Cutting",
    originalName: "cutting.jpeg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Precision cutting stage in fabrication",
    url: "https://lblfabrications.com/assets/images/content/cutting.jpeg",
  },
  routing: {
    id: "routing",
    category: "image",
    name: "Routing",
    originalName: "routing.jpeg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Routing and CNC shaping process",
    url: "https://lblfabrications.com/assets/images/content/routing.jpeg",
  },
  polishing: {
    id: "polishing",
    category: "image",
    name: "Polishing",
    originalName: "polishing.jpeg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Polishing and finishing stage",
    url: "https://lblfabrications.com/assets/images/content/polishing.jpeg",
  },
  installation: {
    id: "installation",
    category: "image",
    name: "Installation",
    originalName: "templating_and_installation.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Installation completion at project site",
    url: "https://lblfabrications.com/assets/images/content/templating_and_installation.jpg",
  },
  templating: {
    id: "templating",
    category: "image",
    name: "Templating",
    originalName: "templating_2.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Templating and digital measurement process",
    url: "https://lblfabrications.com/assets/images/content/templating_2.jpg",
  },
  naturalStone: {
    id: "naturalStone",
    category: "image",
    name: "Natural and manufactured stone",
    originalName: "natural-stone.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Natural and manufactured stone surfaces",
    url: "https://lblfabrications.com/assets/images/buckets/natural-stone.jpg",
  },
  solidSurface: {
    id: "solidSurface",
    category: "image",
    name: "Solid surface",
    originalName: "solid-surface.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 0,
    width: null,
    height: null,
    altText: "Solid surface material sample",
    url: "https://lblfabrications.com/assets/images/buckets/solid-surface.jpg",
  },
};

function section(base: Omit<PublicContentSection, "status" | "settings"> & { settings?: Record<string, unknown> }): PublicContentSection {
  return {
    status: "approved",
    settings: base.settings ?? {},
    ...base,
  };
}

function buildPage(path: string, title: string, seoTitle: string, seoDescription: string, sections: PublicContentSection[]): PublicContentPage {
  return normalizePublicContentPage({
    pageId: `fallback-${path === "/" ? "home" : path.replace(/^\//, "").replace(/\//g, "-")}`,
    siteSlug,
    path,
    title,
    status: "approved",
    seo: {
      title: seoTitle,
      description: seoDescription,
      socialImageAssetId: "heroCountertop",
    },
    sections,
    assetsById: sharedAssets,
  });
}

const fallbackPages: Record<string, PublicContentPage> = {
  "/": buildPage(
    "/",
    "LBL Fabrications",
    "LBL Fabrications | Custom Natural Stone & Solid Surface Fabrication",
    "Premium natural stone and solid surface fabrication for residential and commercial projects across New England and the Mid-Atlantic.",
    [
      section({
        id: "home-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "Custom Fabrication",
          heading: "Precision fabrication for residential and commercial surfaces.",
          body: "LBL Fabrications builds natural stone and solid surface work with a process centered on planning, precision cutting, finishing, and installation.",
          primaryButtonLabel: "Start a Project",
          primaryButtonHref: "/contact",
          secondaryButtonLabel: "View Our Work",
          secondaryButtonHref: "/portfolio",
          backgroundAssetId: "heroCountertop",
          trustItems: ["Springfield, Vermont", "New England & Mid-Atlantic", "Natural stone & solid surface"],
        },
      }),
      section({
        id: "home-capabilities",
        type: "services",
        label: "Capabilities",
        position: 2,
        content: {
          heading: "Capabilities",
          body: "A fabrication workflow designed for custom residential projects, large commercial applications, and specialty material work.",
          items: [
            { eyebrow: "Residential", title: "Custom fabrication", description: "Countertops, vanities, bath surfaces, and built-to-fit applications.", href: "/residential" },
            { eyebrow: "Commercial", title: "Commercial work", description: "Multi-unit, hospitality, retail, healthcare, and education projects.", href: "/commercial" },
            { eyebrow: "Materials", title: "Natural stone & solid surface", description: "Granite, quartz, marble, soapstone, Corian, HIMACS, and more.", href: "/materials" },
            { eyebrow: "Specialty", title: "Specialty builds", description: "Projects that require precision templating, CNC routing, and careful finish coordination.", href: "/portfolio" },
            { eyebrow: "Completion", title: "Installation", description: "Dedicated crews complete delivery and installation at the project site.", href: "/contact" },
          ],
        },
      }),
      section({
        id: "home-projects",
        type: "projects",
        label: "Featured Projects",
        position: 3,
        content: {
          heading: "Featured project types",
          body: "Representative applications based on LBL’s published material and industry capabilities while final project case studies are being prepared.",
          items: [
            { category: "Residential", title: "Kitchen surfaces", description: "Custom countertops and islands fabricated for one-off kitchens and renovations.", imageAssetId: "heroCountertop" },
            { category: "Commercial", title: "Hospitality & public interiors", description: "Surface fabrication for higher-volume commercial environments with finish consistency requirements.", imageAssetId: "cutting" },
            { category: "Multi-unit", title: "Repeatable production work", description: "Applications that require scalable output, careful scheduling, and dependable installation coordination.", imageAssetId: "installation" },
          ],
        },
      }),
      section({
        id: "home-process",
        type: "stats",
        label: "Process",
        position: 4,
        content: {
          heading: "The LBL project process",
          items: [
            { value: "01", label: "Consultation & templating", description: "Detailed digital measurements are captured before fabrication begins." },
            { value: "02", label: "Planning & programming", description: "Templates and material layouts are prepared for precise yields and fit." },
            { value: "03", label: "Cutting & routing", description: "Robotic sawjet and CNC routing shape the project accurately and consistently." },
            { value: "04", label: "Polishing & completion", description: "Pieces are finished, inspected, and prepared for installation." },
          ],
        },
      }),
      section({
        id: "home-materials",
        type: "gallery",
        label: "Materials",
        position: 5,
        content: {
          heading: "Materials and expertise",
          body: "LBL’s published materials include natural and manufactured stone as well as solid surface fabrication.",
          assetIds: ["naturalStone", "solidSurface", "preproduction"],
          captions: [
            "Natural and manufactured stone",
            "Solid surface",
            "Digital planning and slab coordination",
          ],
          layout: "grid",
        },
      }),
      section({
        id: "home-about",
        type: "rich_text",
        label: "About",
        position: 6,
        content: {
          heading: "About LBL Fabrications",
          body: "LBL Fabrications describes itself as a state-of-the-art natural stone and solid surface fabrication company serving residential and commercial projects across New England and the Mid-Atlantic. Based in Springfield, Vermont, the team focuses on precision, process control, and quality fabrication at a wide range of project scales.",
        },
      }),
      section({
        id: "home-testimonial",
        type: "testimonials",
        label: "Case Study Quote",
        position: 7,
        content: {
          heading: "Customer case study",
          items: [
            {
              quote: "Working with LBL Fabrications was a great experience! They combined my ideas and vision with their expertise and experience.",
              name: "Published customer quote",
              role: "Case study testimonial",
              company: "LBL legacy site",
            },
          ],
        },
      }),
      section({
        id: "home-cta",
        type: "cta",
        label: "CTA",
        position: 8,
        content: {
          heading: "Ready to discuss your project?",
          body: "Bring your scope, material questions, and installation timing into the first conversation.",
          buttonLabel: "Start a Project",
          buttonHref: "/contact",
          secondaryButtonLabel: "Explore Materials",
          secondaryButtonHref: "/materials",
        },
      }),
      section({
        id: "home-contact",
        type: "contact",
        label: "Contact",
        position: 9,
        content: {
          heading: "Contact LBL",
          body: "Reach the fabrication team in Springfield, Vermont to discuss scheduling, materials, and scope.",
          phone: "802-885-8677",
          address: "200 Clinton Street, Springfield, VT 05156",
          serviceArea: "New England and the Mid-Atlantic",
        },
      }),
    ],
  ),
  "/residential": buildPage(
    "/residential",
    "Residential Fabrication",
    "Residential Fabrication | LBL Fabrications",
    "Custom natural stone and solid surface fabrication for kitchens, baths, and residential applications.",
    [
      section({
        id: "res-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "Residential",
          heading: "Fabrication tailored to kitchens, baths, and built-to-fit residential work.",
          body: "LBL fabricates residential projects ranging from single bathrooms to full kitchen surfaces using natural stone and solid surface materials.",
          primaryButtonLabel: "Discuss a Residential Project",
          primaryButtonHref: "/contact",
          secondaryButtonLabel: "View Materials",
          secondaryButtonHref: "/materials",
          backgroundAssetId: "heroCountertop",
        },
      }),
      section({
        id: "res-services",
        type: "services",
        label: "Applications",
        position: 2,
        content: {
          heading: "Residential applications",
          items: [
            { title: "Kitchen countertops", description: "Fabrication for primary kitchens, islands, and renovation work." },
            { title: "Vanities", description: "Bathroom surfaces designed for exact site conditions and finish details." },
            { title: "Specialty surfaces", description: "Custom household and consumer applications where precision matters." },
          ],
        },
      }),
      section({
        id: "res-gallery",
        type: "gallery",
        label: "Residential gallery",
        position: 3,
        content: {
          heading: "Representative residential work",
          body: "Published imagery from the fabrication process and completed-surface context while final project photography is being assembled.",
          assetIds: ["heroCountertop", "templating", "installation"],
          captions: ["Countertop detail", "Templating", "Installation finish"],
          layout: "grid",
        },
      }),
      section({
        id: "res-cta",
        type: "cta",
        label: "CTA",
        position: 4,
        content: {
          heading: "Planning a kitchen or bath project?",
          body: "Share your scope, material preference, and timing to start the conversation.",
          buttonLabel: "Start a Project",
          buttonHref: "/contact",
          secondaryButtonLabel: "View Portfolio",
          secondaryButtonHref: "/portfolio",
        },
      }),
    ],
  ),
  "/commercial": buildPage(
    "/commercial",
    "Commercial Fabrication",
    "Commercial Fabrication | LBL Fabrications",
    "Natural stone and solid surface fabrication for hospitality, retail, healthcare, education, office, and multi-unit work.",
    [
      section({
        id: "com-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "Commercial",
          heading: "Commercial surface fabrication built for scale, scheduling, and repeatability.",
          body: "LBL publishes hospitality, retail, healthcare, education, office, and multi-unit housing among its commercial industry capabilities.",
          primaryButtonLabel: "Talk Through a Commercial Scope",
          primaryButtonHref: "/contact",
          secondaryButtonLabel: "View Process",
          secondaryButtonHref: "/portfolio",
          backgroundAssetId: "cutting",
        },
      }),
      section({
        id: "com-services",
        type: "services",
        label: "Industries",
        position: 2,
        content: {
          heading: "Industries served",
          items: [
            { title: "Hospitality", description: "Public-facing spaces that require finish consistency and dependable scheduling." },
            { title: "Retail", description: "Custom surfaces, counters, and built environments with material precision." },
            { title: "Healthcare & education", description: "Commercial applications where accurate fabrication and install coordination are critical." },
            { title: "Office & multi-unit housing", description: "Repeatable project work scaled across larger residential and commercial footprints." },
          ],
        },
      }),
      section({
        id: "com-projects",
        type: "projects",
        label: "Project types",
        position: 3,
        content: {
          heading: "Representative commercial applications",
          items: [
            { category: "Hospitality", title: "Guest-facing counters and surfaces", description: "Material workflows suited for hospitality environments.", imageAssetId: "routing" },
            { category: "Retail", title: "Custom fixture surfaces", description: "Counter and display work requiring exact site fit and finish.", imageAssetId: "polishing" },
            { category: "Multi-unit", title: "Repeatable fabrication packages", description: "Scaled surface fabrication for larger rollout-style scopes.", imageAssetId: "installation" },
          ],
        },
      }),
      section({
        id: "com-cta",
        type: "cta",
        label: "CTA",
        position: 4,
        content: {
          heading: "Need a fabrication partner for a larger commercial build?",
          body: "Bring material requirements, drawings, or bid timelines into the first conversation.",
          buttonLabel: "Discuss a Project",
          buttonHref: "/contact",
        },
      }),
    ],
  ),
  "/materials": buildPage(
    "/materials",
    "Materials",
    "Materials | LBL Fabrications",
    "Natural and manufactured stone plus solid surface fabrication expertise from LBL Fabrications.",
    [
      section({
        id: "mat-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "Materials",
          heading: "Natural stone and solid surface expertise for custom fabrication.",
          body: "LBL’s published material focus includes natural and manufactured stone as well as solid surface fabrication.",
          primaryButtonLabel: "Talk Materials",
          primaryButtonHref: "/contact",
          secondaryButtonLabel: "View Capabilities",
          secondaryButtonHref: "/commercial",
          backgroundAssetId: "naturalStone",
        },
      }),
      section({
        id: "mat-gallery",
        type: "gallery",
        label: "Material gallery",
        position: 2,
        content: {
          heading: "Material families",
          assetIds: ["naturalStone", "solidSurface"],
          captions: [
            "Natural and manufactured stone: marble, granite, quartz, soapstone",
            "Solid surface: DuPont Corian, LG HIMACS, and more",
          ],
          layout: "split",
        },
      }),
      section({
        id: "mat-rich",
        type: "rich_text",
        label: "Material copy",
        position: 3,
        content: {
          heading: "Choosing the right material",
          body: "Material selection changes the performance, finish, and installation details of every project. LBL’s published capabilities emphasize natural stone and solid surface fabrication for both residential and commercial applications.",
          bullets: ["Granite", "Quartz", "Marble", "Soapstone", "Solid surface"],
        },
      }),
      section({
        id: "mat-cta",
        type: "cta",
        label: "CTA",
        position: 4,
        content: {
          heading: "Need help narrowing the right surface?",
          body: "Start with the application, finish requirement, and material category you are considering.",
          buttonLabel: "Contact LBL",
          buttonHref: "/contact",
        },
      }),
    ],
  ),
  "/portfolio": buildPage(
    "/portfolio",
    "Portfolio",
    "Portfolio | LBL Fabrications",
    "Representative fabrication work, process imagery, and application categories from LBL Fabrications.",
    [
      section({
        id: "port-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "Portfolio",
          heading: "Representative fabrication work and process context.",
          body: "The current portfolio highlights project types and fabrication process imagery while final project case studies are being assembled.",
          primaryButtonLabel: "Start a Project",
          primaryButtonHref: "/contact",
          secondaryButtonLabel: "View Process",
          secondaryButtonHref: "/about",
          backgroundAssetId: "installation",
        },
      }),
      section({
        id: "port-projects",
        type: "projects",
        label: "Projects",
        position: 2,
        content: {
          heading: "Featured work categories",
          items: [
            { category: "Residential", title: "Kitchen countertop fabrication", description: "Single-home projects requiring accurate templating and clean finish details.", imageAssetId: "heroCountertop" },
            { category: "Commercial", title: "Retail and hospitality surfaces", description: "Larger-scope fabrication aligned to commercial scheduling and repeatability.", imageAssetId: "cutting" },
            { category: "Process", title: "Templating to installation", description: "A complete fabrication sequence from field measurement through install.", imageAssetId: "templating" },
          ],
        },
      }),
      section({
        id: "port-gallery",
        type: "gallery",
        label: "Gallery",
        position: 3,
        content: {
          heading: "Process imagery",
          assetIds: ["preproduction", "cutting", "routing", "polishing", "installation"],
          captions: ["Planning", "Cutting", "Routing", "Polishing", "Installation"],
          layout: "grid",
        },
      }),
    ],
  ),
  "/about": buildPage(
    "/about",
    "About LBL",
    "About | LBL Fabrications",
    "About LBL Fabrications, its process, fabrication focus, and regional service footprint.",
    [
      section({
        id: "about-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "About LBL",
          heading: "Craftsmanship, precision, and a fabrication process built for demanding surface work.",
          body: "LBL Fabrications publishes a process-led approach to natural stone and solid surface work for residential and commercial clients across New England and the Mid-Atlantic.",
          primaryButtonLabel: "Contact LBL",
          primaryButtonHref: "/contact",
          secondaryButtonLabel: "View Materials",
          secondaryButtonHref: "/materials",
          backgroundAssetId: "preproduction",
        },
      }),
      section({
        id: "about-rich",
        type: "rich_text",
        label: "Company story",
        position: 2,
        content: {
          heading: "Precision fabrication from Springfield, Vermont",
          body: "LBL Fabrications describes its Springfield, Vermont facility as serving projects throughout New England and the Mid-Atlantic. Its published process emphasizes digital templating, material planning, robotic sawjet cutting, CNC routing, polishing, and installation.",
        },
      }),
      section({
        id: "about-stats",
        type: "stats",
        label: "Verified details",
        position: 3,
        content: {
          heading: "Published company details",
          items: [
            { value: "50,000", label: "Square foot facility", description: "Published on the legacy site." },
            { value: "75", label: "Combined technician years", description: "Published on the legacy site." },
            { value: "50+", label: "Material options", description: "Published on the legacy site." },
          ],
        },
      }),
      section({
        id: "about-process",
        type: "services",
        label: "Process highlights",
        position: 4,
        content: {
          heading: "Process highlights",
          items: [
            { title: "Digital templating", description: "Field measurements are captured digitally before fabrication begins." },
            { title: "Robotic sawjet cutting", description: "Cutting programs are recorded and executed for precision output." },
            { title: "CNC routing and polishing", description: "Edges and finishes are shaped and polished before final inspection." },
            { title: "Installation crews", description: "Dedicated teams complete project-site delivery and installation." },
          ],
        },
      }),
    ],
  ),
  "/contact": buildPage(
    "/contact",
    "Contact LBL",
    "Contact | LBL Fabrications",
    "Contact LBL Fabrications in Springfield, Vermont to discuss natural stone and solid surface projects.",
    [
      section({
        id: "contact-hero",
        type: "hero",
        label: "Hero",
        position: 1,
        content: {
          eyebrow: "Contact",
          heading: "Bring your project scope, material questions, and timing into the conversation.",
          body: "LBL Fabrications serves New England and the Mid-Atlantic from Springfield, Vermont.",
          primaryButtonLabel: "Call 802-885-8677",
          primaryButtonHref: "tel:8028858677",
          secondaryButtonLabel: "View Materials",
          secondaryButtonHref: "/materials",
          backgroundAssetId: "installation",
        },
      }),
      section({
        id: "contact-band",
        type: "contact",
        label: "Contact band",
        position: 2,
        content: {
          heading: "Talk with the team",
          body: "Use the published phone and location details to begin your project conversation.",
          phone: "802-885-8677",
          address: "200 Clinton Street, Springfield, VT 05156",
          serviceArea: "New England and the Mid-Atlantic",
        },
      }),
      section({
        id: "contact-cta",
        type: "cta",
        label: "CTA",
        position: 3,
        content: {
          heading: "Need to align drawings, material, and installation timing?",
          body: "LBL’s published process is built for detailed planning from template through install.",
          buttonLabel: "Call Now",
          buttonHref: "tel:8028858677",
          secondaryButtonLabel: "See the Process",
          secondaryButtonHref: "/about",
        },
      }),
    ],
  ),
};

export function getFallbackPageContent(path: string): PublicContentPage {
  return fallbackPages[path] ?? fallbackPages["/"];
}

export function getFallbackHomepageContent(): PublicContentPage {
  return getFallbackPageContent("/");
}
